<?xml version="1.0" encoding="utf-8"?><Database Name="BTSDB" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\BTSDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BTSDBConn" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="routeID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="routeFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="routeTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>