//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace PlsCan_Run.ServiceReference3 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Route", Namespace="http://schemas.datacontract.org/2004/07/PlsCan_Run.Web")]
    public partial class Route : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string priceField;
        
        private string routeFromField;
        
        private string routeIDField;
        
        private string routeToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string price {
            get {
                return this.priceField;
            }
            set {
                if ((object.ReferenceEquals(this.priceField, value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string routeFrom {
            get {
                return this.routeFromField;
            }
            set {
                if ((object.ReferenceEquals(this.routeFromField, value) != true)) {
                    this.routeFromField = value;
                    this.RaisePropertyChanged("routeFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string routeID {
            get {
                return this.routeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.routeIDField, value) != true)) {
                    this.routeIDField = value;
                    this.RaisePropertyChanged("routeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string routeTo {
            get {
                return this.routeToField;
            }
            set {
                if ((object.ReferenceEquals(this.routeToField, value) != true)) {
                    this.routeToField = value;
                    this.RaisePropertyChanged("routeTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference3.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Service1/Get_All_Sales", ReplyAction="urn:Service1/Get_All_SalesResponse")]
        System.IAsyncResult BeginGet_All_Sales(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> EndGet_All_Sales(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Service1/Get_Find_Destination", ReplyAction="urn:Service1/Get_Find_DestinationResponse")]
        System.IAsyncResult BeginGet_Find_Destination(string Names, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> EndGet_Find_Destination(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : PlsCan_Run.ServiceReference3.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Get_All_SalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Get_All_SalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Get_Find_DestinationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Get_Find_DestinationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PlsCan_Run.ServiceReference3.Service1>, PlsCan_Run.ServiceReference3.Service1 {
        
        private BeginOperationDelegate onBeginGet_All_SalesDelegate;
        
        private EndOperationDelegate onEndGet_All_SalesDelegate;
        
        private System.Threading.SendOrPostCallback onGet_All_SalesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGet_Find_DestinationDelegate;
        
        private EndOperationDelegate onEndGet_Find_DestinationDelegate;
        
        private System.Threading.SendOrPostCallback onGet_Find_DestinationCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<Get_All_SalesCompletedEventArgs> Get_All_SalesCompleted;
        
        public event System.EventHandler<Get_Find_DestinationCompletedEventArgs> Get_Find_DestinationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PlsCan_Run.ServiceReference3.Service1.BeginGet_All_Sales(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGet_All_Sales(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> PlsCan_Run.ServiceReference3.Service1.EndGet_All_Sales(System.IAsyncResult result) {
            return base.Channel.EndGet_All_Sales(result);
        }
        
        private System.IAsyncResult OnBeginGet_All_Sales(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PlsCan_Run.ServiceReference3.Service1)(this)).BeginGet_All_Sales(callback, asyncState);
        }
        
        private object[] OnEndGet_All_Sales(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> retVal = ((PlsCan_Run.ServiceReference3.Service1)(this)).EndGet_All_Sales(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGet_All_SalesCompleted(object state) {
            if ((this.Get_All_SalesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Get_All_SalesCompleted(this, new Get_All_SalesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Get_All_SalesAsync() {
            this.Get_All_SalesAsync(null);
        }
        
        public void Get_All_SalesAsync(object userState) {
            if ((this.onBeginGet_All_SalesDelegate == null)) {
                this.onBeginGet_All_SalesDelegate = new BeginOperationDelegate(this.OnBeginGet_All_Sales);
            }
            if ((this.onEndGet_All_SalesDelegate == null)) {
                this.onEndGet_All_SalesDelegate = new EndOperationDelegate(this.OnEndGet_All_Sales);
            }
            if ((this.onGet_All_SalesCompletedDelegate == null)) {
                this.onGet_All_SalesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGet_All_SalesCompleted);
            }
            base.InvokeAsync(this.onBeginGet_All_SalesDelegate, null, this.onEndGet_All_SalesDelegate, this.onGet_All_SalesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PlsCan_Run.ServiceReference3.Service1.BeginGet_Find_Destination(string Names, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGet_Find_Destination(Names, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> PlsCan_Run.ServiceReference3.Service1.EndGet_Find_Destination(System.IAsyncResult result) {
            return base.Channel.EndGet_Find_Destination(result);
        }
        
        private System.IAsyncResult OnBeginGet_Find_Destination(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Names = ((string)(inValues[0]));
            return ((PlsCan_Run.ServiceReference3.Service1)(this)).BeginGet_Find_Destination(Names, callback, asyncState);
        }
        
        private object[] OnEndGet_Find_Destination(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> retVal = ((PlsCan_Run.ServiceReference3.Service1)(this)).EndGet_Find_Destination(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGet_Find_DestinationCompleted(object state) {
            if ((this.Get_Find_DestinationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Get_Find_DestinationCompleted(this, new Get_Find_DestinationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Get_Find_DestinationAsync(string Names) {
            this.Get_Find_DestinationAsync(Names, null);
        }
        
        public void Get_Find_DestinationAsync(string Names, object userState) {
            if ((this.onBeginGet_Find_DestinationDelegate == null)) {
                this.onBeginGet_Find_DestinationDelegate = new BeginOperationDelegate(this.OnBeginGet_Find_Destination);
            }
            if ((this.onEndGet_Find_DestinationDelegate == null)) {
                this.onEndGet_Find_DestinationDelegate = new EndOperationDelegate(this.OnEndGet_Find_Destination);
            }
            if ((this.onGet_Find_DestinationCompletedDelegate == null)) {
                this.onGet_Find_DestinationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGet_Find_DestinationCompleted);
            }
            base.InvokeAsync(this.onBeginGet_Find_DestinationDelegate, new object[] {
                        Names}, this.onEndGet_Find_DestinationDelegate, this.onGet_Find_DestinationCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PlsCan_Run.ServiceReference3.Service1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<PlsCan_Run.ServiceReference3.Service1>, PlsCan_Run.ServiceReference3.Service1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<PlsCan_Run.ServiceReference3.Service1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGet_All_Sales(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Get_All_Sales", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> EndGet_All_Sales(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> _result = ((System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route>)(base.EndInvoke("Get_All_Sales", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGet_Find_Destination(string Names, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Names;
                System.IAsyncResult _result = base.BeginInvoke("Get_Find_Destination", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> EndGet_Find_Destination(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route> _result = ((System.Collections.ObjectModel.ObservableCollection<PlsCan_Run.ServiceReference3.Route>)(base.EndInvoke("Get_Find_Destination", _args, result)));
                return _result;
            }
        }
    }
}
